name: create-nginx-action
on: [push]
jobs:
  check-nginx-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g nginx
      - run: nginx -v
